### ISSUE TITLE
Pico W Detector Details

### ISSUE THREAD

**Issue by URL42** [veebch/peeperpam#1]
Hello! I was wondering if you could provide a bit more detail on the detector connections. Maybe a diagram or a picture where I can see the wires? I'm not great at the electrical engineering part, but I love the idea of the detector. I'm going to attempt to train the model to recognize raccoons because I have a family of racoons making my cat's life a nightmare lol, but I never catch them in the act!

**Comment by veebch** [comment]
Hey there,  Racooncam sounds like a winner. I'll add a photo to the readme this  morning. Hopefully the janky soldering will not cause too many screams on the internet. I'll leave this open until I actually add the photo.

**Comment by veebch** [comment]
Done! I want a racoon update once it's all done :)

**Comment by URL42** [comment]
Exactly what I needed. Thank you very much!!! Will let you know how it goes with the raccoons lol!
